/// @description Variables

global.playerControl = 1;
walkSpeed = 4;
dir = 0;
walkSoundDelay = 20;
nearbyNPC = noone;
nearbyDoor = noone;
lookRange = 17;
npcPrompt = noone;
npcPromptDoor = noone;
is_dashing = false;
dash_speed = 30;
dash_cooldown = 120;
letter = 0;
global.zone1Pass = false;
global.zone2Pass = false;
global.zone3Pass = false;
global.lystOutfit = 0;
global.segguOutfit1 = 0;
global.segguOutfit2 = 0;